<a href="https://colab.research.google.com/github/MarcosRamirezMontes/Diplomado-IA/blob/master/2B_Xor_JCOR_Perceptron_backpropagation_DIPLOMADO_Al.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [14]:
# cargamos las 4 combinaciones de las compuertas XOR
training_data = np.array([[1,0,0], [0,1,0], [0,0,1], [1,1,0],[0,1,1],[1,0,1],[1,1,1]])

# y estos son los resultados que se obtienen, en el mismo orden
target_data = np.array([[[1],[1],[0],[0]], [[0],[0],[1],[0]], [[0],[0],[0],[1]],
                      [[1],[1],[1],[0]], [[0],[0],[1],[1]], [[1],[1],[0],[1]], [[1],[1],[1],[1]]] )

In [15]:
print(target_data)

[[[1]
  [1]
  [0]
  [0]]

 [[0]
  [0]
  [1]
  [0]]

 [[0]
  [0]
  [0]
  [1]]

 [[1]
  [1]
  [1]
  [0]]

 [[0]
  [0]
  [1]
  [1]]

 [[1]
  [1]
  [0]
  [1]]

 [[1]
  [1]
  [1]
  [1]]]


In [16]:
print(training_data)

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


# Definimos una arquitectura de red neuronal

In [17]:
model = Sequential()
# En el primer dense son las capas
model.add(Dense(16, input_dim=3, activation='relu'))
# En el segundo dense son las neuronas que necesito
model.add(Dense(4, activation='sigmoid'))

In [18]:
model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['binary_accuracy'])

# Entrenamiento de la red

In [19]:
model.fit(training_data, target_data , epochs=500)

Epoch 1/500
1/1 [==============================] - 1s 740ms/step - loss: 0.2726 - binary_accuracy: 0.4643
Epoch 2/500
1/1 [==============================] - 0s 33ms/step - loss: 0.2716 - binary_accuracy: 0.4643
Epoch 3/500
1/1 [==============================] - 0s 19ms/step - loss: 0.2706 - binary_accuracy: 0.4643
Epoch 4/500
1/1 [==============================] - 0s 14ms/step - loss: 0.2697 - binary_accuracy: 0.5000
Epoch 5/500
1/1 [==============================] - 0s 12ms/step - loss: 0.2687 - binary_accuracy: 0.5000
Epoch 6/500
1/1 [==============================] - 0s 20ms/step - loss: 0.2678 - binary_accuracy: 0.5000
Epoch 7/500
1/1 [==============================] - 0s 16ms/step - loss: 0.2668 - binary_accuracy: 0.5000
Epoch 8/500
1/1 [==============================] - 0s 14ms/step - loss: 0.2659 - binary_accuracy: 0.5000
Epoch 9/500
1/1 [==============================] - 0s 15ms/step - loss: 0.2649 - binary_accuracy: 0.5000
Epoch 10/500
1/1 [==============================] - 0s

In [20]:
# evaluamos el modelo
scores = model.evaluate(training_data, target_data)

1/1 [==============================] - 0s 124ms/step - loss: 0.0274 - binary_accuracy: 1.0000


In [21]:

print (model.predict(training_data).round())

1/1 [==============================] - 0s 95ms/step
[[1. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 1. 1. 0.]
 [0. 0. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 1.]]
